# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import requests
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QImage, QPixmap
from PyQt5.QtWidgets import QLabel, QWidget


class Ui_wechatqrcode(object):
    def setupUi(self, wechatqrcode):
        wechatqrcode.setObjectName("wechatqrcode")
        wechatqrcode.resize(1000, 800)
        wechatqrcode.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(wechatqrcode)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 50))
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.lineEdit, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setMinimumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.pushButton.setFont(font)
        self.pushButton.setIconSize(QtCore.QSize(32, 32))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 0, 1, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1034, 606))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayoutWidget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1031, 601))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.scrollArea, 1, 0, 1, 2)
        wechatqrcode.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(wechatqrcode)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1054, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        wechatqrcode.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(wechatqrcode)
        self.statusbar.setObjectName("statusbar")
        wechatqrcode.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(wechatqrcode)
        QtCore.QMetaObject.connectSlotsByName(wechatqrcode)

    def retranslateUi(self, wechatqrcode):
        _translate = QtCore.QCoreApplication.translate
        wechatqrcode.setWindowTitle(_translate("wechatqrcode", "MainWindow"))
        self.pushButton.setToolTip(_translate("wechatqrcode", "输入公众号链接点击获取"))
        self.pushButton.setText(_translate("wechatqrcode", "获取二维码"))
        self.menu.setTitle(_translate("wechatqrcode", "菜单"))
        self.pushButton.clicked.connect(self.search)

    def search(self):
        url = "http://photocdn.sohu.com/20120128/Img333056814.jpg"
        res = requests.get(url)
        img = QImage.fromData(res.content)

        self.filewidget = QWidget()
        self.filewidget.setMinimumSize(350, 3000)

        positions = [(i, j) for i in range(4) for j in range(10)]  # 规定每行每列多少数据  第一个是行 第二个是列
        for position, j in zip(positions, range(40)):  # 在for里面新建qlabel 这样每个label才会是独立的
            myimg = QLabel(self.filewidget)
            myimg.setScaledContents(True)
            myimg.setPixmap(QPixmap.fromImage(img))
            myimg.setFixedSize(200, 200)
            myimg.move(250* position[0] , 250 * position[1])
            # self.gridLayout.addWidget(myimg,*position)
        self.scrollArea.setWidget(self.filewidget)
